FROM python:3.11

# 
WORKDIR /user/app

# 
COPY ./app/requirements.txt /user/requirements.txt

# 
RUN pip install --no-cache-dir --upgrade -r /user/requirements.txt
RUN pip install "python-jose"
RUN pip install 'pydantic[email]'
RUN pip install passlib[bcrypt]

COPY ./app /user/app

# gunicorn -k uvicorn.workers.UvicornWorker run:app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]