FROM python:3.11

# 
WORKDIR /todo/app

# 
COPY ./app/requirements.txt /todo/requirements.txt

# 


RUN pip install --no-cache-dir --upgrade -r /todo/requirements.txt
RUN pip install "python-jose"
RUN pip install 'pydantic[email]'
# 
COPY ./app /todo/app
EXPOSE 8001
# 
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]